version: "3"

networks:
  credi-nord-network:
    driver: bridge
    name: credi-nord-network
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="weather-alert"
    ports:
      - 27017:27017
    networks:
      - credi-nord-network
  weather-api:
    build:
      context: .
      dockerfile: dev.api.dockerfile
    image: credi-nord_weather-api
    container_name: cn-api
    environment:
      - PRODUCTION="true"
    ports:
      - 3333:3333
    depends_on:
      - mongodb
    volumes:
      - ./apps:/app/apps:ro
      - ./libs:/app/libs:ro
    restart: always
    networks:
      - credi-nord-network
